### ISSUE TITLE
Adding the proper typography and type styles override

### ISSUE THREAD

**Issue by znegrin** [athenianco/athenian-webapp#72]
I will add the Cerebri typography to the webapp and override the styles to set up the proper sizes [according to the prototypes](https://zurinegrn558160.invisionapp.com/overview/Athenian---Dashboard-ck6gn9es0003g01ab2k2y2k3p/screens).

**Comment by znegrin** [comment]
@dpordomingo I have several doubts about how to proceed with this in terms of how to override the existing work. Please feel free to ping me here or at Slack so I can start working on it properly.

Thank you!

**Comment by dpordomingo** [comment]
About typography, for example, SB Admin 2 defines its fonts [with `$font-family-sans-serif` variable](https://github.com/BlackrockDigital/startbootstrap-sb-admin-2/blob/master/scss/_variables.scss#L40), which could be overrided from `src/sass/_overrides.scss` as done [in this other situations](https://github.com/athenianco/athenian-webapp/blob/master/src/sass/_overrides.scss#L29).

**Comment by znegrin** [comment]
These changes are made in #74.
