### ISSUE TITLE
Adding proper colors and overriding exising classes

### ISSUE THREAD

**Issue by znegrin** [athenianco/athenian-webapp#73]
I will add the proper color variables to the webapp and override the styles to set up the proper styles [according to the prototypes](https://zurinegrn558160.invisionapp.com/overview/Athenian---Dashboard-ck6gn9es0003g01ab2k2y2k3p/screens).

**Comment by dpordomingo** [comment]
About colors, please consider this PR
https://github.com/athenianco/athenian-webapp/pull/71/files#diff-f8f16d82a4147d8a9d954a0e782b2f87

I'd suggest you add my fork, and start your work from the tip of my `thumbnails-active-effect` branch. It'll be a pain until we merge all the pending PRs, but I think it would be better if we do this way.

**Comment by znegrin** [comment]
Perfect! I will proceed as you suggest.
